[consolidatorService.config]
KAFKA_BOOTSTRAP_NODE = "kafka.mosip.svc.cluster.local:9092"
REGISTERED_WEBSUB_TOPICS_TOPIC = "registered-websub-topics"
CONSOLIDATED_WEBSUB_TOPICS_TOPIC = "consolidated-websub-topics"
WEBSUB_SUBSCRIBERS_TOPIC = "registered-websub-subscribers"
CONSOLIDATED_WEBSUB_SUBSCRIBERS_TOPIC = "consolidated-websub-subscribers"
POLLING_INTERVAL = 10.0
GRACEFUL_CLOSE_PERIOD = 5.0

[consolidatorService.security]
SECURITY_PROTOCOL = "SASL_PLAINTEXT"
SASL_MECHANISM = "SCRAM-SHA-256"
SASL_USERNAME = "user1"
SASL_PASSWORD = "tMeGNekOCo"
