[kafkaHub.config]
SECURITY_ON = true
SERVER_ID = "server-1"
KAFKA_BOOTSTRAP_NODE = "kafka.mosip.svc.cluster.local:9092"
REGISTERED_WEBSUB_TOPICS_TOPIC = "registered-websub-topics"
CONSOLIDATED_WEBSUB_TOPICS_TOPIC = "consolidated-websub-topics"
WEBSUB_SUBSCRIBERS_TOPIC = "registered-websub-subscribers"
CONSOLIDATED_WEBSUB_SUBSCRIBERS_TOPIC = "consolidated-websub-subscribers"
POLLING_INTERVAL = 10.0
GRACEFUL_CLOSE_PERIOD = 5.0
HUB_PORT = 9191
MESSAGE_DELIVERY_RETRY_INTERVAL = 3.0
MESSAGE_DELIVERY_COUNT = 3
MESSAGE_DELIVERY_TIMEOUT = 60.0
MOSIP_AUTH_BASE_URL = "${mosip.api.internal.url}/v1/authmanager"
MOSIP_AUTH_VALIDATE_TOKEN_URL = "/authorize/admin/validateToken"

[kafkaHub.security]
SECURITY_PROTOCOL = "SASL_PLAINTEXT"
SASL_MECHANISM = "SCRAM-SHA-256"
SASL_USERNAME = "user1"
SASL_PASSWORD = "tMeGNekOCo"
